apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: samplelinuxworkload
  labels:
    app: my-app
spec:
  selector:
    app: my-app
type: LoadBalancer
  ports:
  name: my-app-port
    - protocol: TCP
      port: 8080
      targetPort: 80
